### ISSUE TITLE
Does primeng-shadowdom-directives support p-table?

### ISSUE THREAD

**Issue by msbasanth** [maitrungduc1410/primeng-shadowdom-directives#6]
Hi,

We are facing issues when placing p-table inside a custom element created using LitElement. i.e. when we have p-table inside the shadowDom. Does primeng-shadowdom-directives support p-table?

**Comment by papb** [comment]
According to the readme, no. But what issues are you facing? I would expect p-table to work automatically

**Comment by maitrungduc1410** [comment]
The p-table should work fine, what issue are u facing?

the library is to solve issue with all component has “overlay” of primeNG inside ShadowDOM (lit-element of course), p-table is not such components, so I expect it should work automatically.

**Comment by maitrungduc1410** [comment]
If you’re facing issue where no style applied to your table inside shadowDOM, then it is how it is, not just for primeng, for other libs also. Simply add primeng CSS files directly to your component. I already commented [here](https://github.com/primefaces/primeng/issues/9471#issuecomment-991587838)

**Comment by msbasanth** [comment]
Thanks @maitrungduc1410 @papb for your quick response.

One observation is, table rendering is having issues when we use the virtual scroll, when disabling the virtual scroll table rendering looks fine.

This is the sample virtual p-table I kept in a simple custom element,
https://github.com/msbasanth/primeng-shadowdom

This is the current structure,
![image](https://user-images.githubusercontent.com/17777813/197451926-221374ed-8f96-4cf0-8b7d-dc9fc44f026c.png)

Another observation is when we dynamically add table containers through dev tools themes are coming and working.

I saw your solution to add styles directly to container Angular Component, but in my case I have a custom element instead of Angular Component.
I have not tried applying style inside shadow dom. Do we have a way to add priming CSS files directly to table-container (custom element)?

**Comment by papb** [comment]
> I have not tried applying style inside shadow dom.

I had to do exactly this. In summary:

```ts
// <app-root> component

import { Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<app-main></app-main>',
  encapsulation: ViewEncapsulation.ShadowDom,
  styleUrls: ['../styles.scss'],
})
export class AppComponent {}
```

```scss
// styles.scss

@import "../node_modules/primeicons/primeicons.css";
@import "../node_modules/primeflex/primeflex.css";
@import "../node_modules/primeng/resources/themes/saga-blue/theme.css";
@import "../node_modules/primeng/resources/primeng.min.css";
@import "./assets/styles/simplified-primeng-showcase/app.scss";

html, body {
  margin: 0;
  padding: 0;
}

label {
  cursor: inherit;
}
```

The above basically makes all PrimeNG css available within the shadow dom.

Note: `./assets/styles/simplified-primeng-showcase/app.scss` is a bunch of styles that I took from [here](https://github.com/primefaces/primeng/blob/1d5c37fc5c69b4d6b902dd3dd07b32838be1953e/src/assets/showcase/styles/primeng.css) and adapted. You might not need it.

Note: you will need to heavily increase the size budget for `anyComponentStyle` within `angular.json` though (I put `10m` on mine):

```jsonc
// angular.json excerpt

{
  "projects": {
    "my-cool-project": {
      "architect": {
        "build": {
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "5mb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "5mb",
                  "maximumError": "10mb"
                }
              ]
            }
          }
        }
      }
    }
  }
}
```

Thankfully this super large size is not a problem for me.
